export type TagVariant =
  | "three"
  | "websockets"
  | "react"
  | "redis"
  | "gray"
  | "html"
  | "css"
  | "javascript"
  | "node"
  | "next"
  | "kubernetes"
  | "postgresql"
  | "ogl"
  | "glsl"
  | "python"
  | "fastapi"
  | "streamlit"
  | "pandas"
  | "docker"
  | "plotly"
  | "sqlite"
  | "tailwind"
  | "csharp"
  | "dotnet"
  | "watchdog"
  | "tkinter"
  | "apscheduler"
  | "rest"
  | "angular"
  | "typescript"
  | "recharts"
  | "pyyaml"
  | "pystray"
  | "plyer"
  | "vite"
  | "vitest"
  | "pwa"
  | "framermotion";

export const tagLabels = {
  three: "Three.js",
  websockets: "WebSockets",
  react: "React",
  redis: "Redis",
  gray: "Gray",
  html: "HTML",
  css: "CSS",
  javascript: "JavaScript",
  node: "Node.js",
  next: "Next.js",
  kubernetes: "Kubernetes",
  postgresql: "PostgreSQL",
  ogl: "OGL.js",
  glsl: "GLSL",
  python: "Python",
  fastapi: "FastAPI",
  streamlit: "Streamlit",
  pandas: "Pandas",
  docker: "Docker",
  plotly: "Plotly",
  sqlite: "SQLite",
  tailwind: "Tailwind",
  csharp: "C#",
  dotnet: ".NET",
  watchdog: "Watchdog",
  tkinter: "CustomTkinter",
  apscheduler: "APScheduler",
  rest: "REST API",
  angular: "Angular",
  typescript: "TypeScript",
  recharts: "Recharts",
  pyyaml: "PyYAML",
  pystray: "pystray",
  plyer: "plyer",
  vite: "Vite",
  vitest: "Vitest",
  pwa: "PWA",
  framermotion: "Framer Motion",
} as const satisfies Record<TagVariant, string>;
